services:
  nginx-ingress:
    image: shalmaka/nginx-ingress
    networks:
      external:
        ipv4_address: ${STATIC_IP}  # IP address for macvlan network
      internal: {}  # Internal communication between containers
    environment:
      EXTERNAL_IP: "${STATIC_IP}"
      INTERFACE_HTTPS_PORT: "${INTERFACE_HTTPS_PORT}"
      UPSTREAM_SERVER: "${UPSTREAM_SERVER}"
      UPSTREAM_PORT: "${UPSTREAM_PORT}"
      SERVER_NAME: "${SERVER_NAME}"
      CERT_FILENAME: "${CERT_FILENAME}"
      KEY_FILENAME: "${KEY_FILENAME}"
    volumes:
      - ./certs:/www/certs:ro
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

networks:
  external:
    external: true
    name: ${MACVLAN_NAME}  # Using the macvlan network name from .env
  internal:
    internal: true  # This makes the network isolated and internal
    driver: bridge  # Internal network using Docker's default bridge driver
